default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DATABASE_URL'] %>
  username: postgres
  password:
  pool: 5

production:
  <<: *default
  database: app_production

development:
  <<: *default
  database: app_development


test:
  <<: *default
  database: app_test