version: '3'
services:
  postgres:
    image: postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  backend:
    build: ./backend
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./backend:/app
    depends_on:
      - postgres
  frontend:
    image: node
    working_dir: /app
    command: npm start
    volumes:
      - ./frontend:/app
  nginx:
    image: nginx
    ports:
      - '80:80'
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
